name: CICD

on:
  push:
    branches: [ "main" ]



jobs:
  test:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}


    - name: Telnet Send
      run: python3 script.py
